import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/shared/styles/globals.css";
import { CssDebugger } from "@/shared/components/css-debugger";
import { Toaster } from "@/shared/components/shadcn/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`${inter.className} antialiased`}>
				{children}
				<Toaster richColors />
				<CssDebugger />
			</body>
		</html>
	);
}
